services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    volumes:
      - db_data:/var/lib/postgresql/data

  nextjs:
    build:
      context: ./apps/web
    ports:
      - "3000:3000"
    env_file:
      - .env
    command: npm run dev
    volumes:
      - ./apps/web:/app
      - /app/node_modules
    working_dir: /app
    depends_on:
      - phoenix

  phoenix:
    build:
      context: ./apps/api
    ports:
      - "4000:4000"
    command: mix phx.server
    env_file:
      - .env
    volumes:
      - ./apps/api:/app
      - /app/deps
    # environment:
    #   MIX_ENV: dev
    #   SECRET_KEY_BASE: "your_secret_key"
    working_dir: /app
    depends_on:
      - postgres

volumes:
  db_data: