version: '3'

services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - 5436:5432
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}